package ollama

import (
	_ "embed"
	"fmt"

	"gopkg.in/yaml.v3"
)

//go:generate go run ./internal/gen

// PopularModel is one entry from the bundled popular-models snapshot — ONE per
// parameter-size variant. The list is a BAKED, embedded YAML file
// (internal/ollama/models.yaml) — there is NO runtime network call. It is captured
// from ollama.com/library?sort=popular (the most-pulled models) by the regeneration
// tool (`make models-refresh`); maintainers refresh it, the program only reads it.
//
// Each size variant of a model is its OWN entry, because each is a distinct,
// separately-pullable model with its own parameter count and download size. Name is
// the exact pullable reference including the size tag (e.g. "qwen2.5:7b");
// Parameters is that single size (e.g. "7b"); DownloadSize is the bytes for THAT
// tag's manifest (0 when unknown — the CLI renders "—"). A model with no size
// variants (e.g. an embedding model like nomic-embed-text) is a single entry whose
// Name is the bare model name and whose Parameters is "". RepoURL is the model's
// ollama.com/library page (shared by all of a model's variants).
type PopularModel struct {
	Name         string `json:"name" yaml:"name"`
	Parameters   string `json:"parameters,omitempty" yaml:"parameters,omitempty"`
	DownloadSize int64  `json:"download_size,omitempty" yaml:"download_size,omitempty"`
	RepoURL      string `json:"repo_url" yaml:"repo_url"`
	PullCount    string `json:"pull_count,omitempty" yaml:"pull_count,omitempty"`
}

// modelsYAML is the bundled snapshot, embedded at build time. It is regenerated by
// internal/ollama/internal/gen (see the //go:generate directive above and the
// `make models-refresh` target). The runtime never re-scrapes ollama.com.
//
//go:embed models.yaml
var modelsYAML []byte

// popularFile is the on-disk shape of models.yaml: a top-level `models:` list.
type popularFile struct {
	Models []PopularModel `yaml:"models"`
}

// Popular returns the bundled popular-models snapshot, parsed from the embedded
// YAML. It performs NO network access and never fails in normal operation (the
// snapshot is compiled into the binary); a malformed embedded file is the only
// error path. It is the entry point the CLI/TUI wire (overridable in tests via the
// package var below).
var Popular = func() ([]PopularModel, error) { return loadPopular() }

// loadPopular parses the embedded models.yaml into the snapshot list.
func loadPopular() ([]PopularModel, error) {
	var file popularFile
	if err := parseInto(modelsYAML, &file); err != nil {
		return nil, fmt.Errorf("ollama: parsing bundled popular-models snapshot: %w", err)
	}
	return file.Models, nil
}

// parseInto unmarshals a models.yaml document into file; split out so the parse
// error path is unit-testable without a malformed embedded asset.
func parseInto(data []byte, file *popularFile) error {
	return yaml.Unmarshal(data, file)
}
